# Generated by Django 5.0.7 on 2024-08-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_id', models.CharField(max_length=100)),
                ('Patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Modality', models.CharField(max_length=10)),
                ('Study_Date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
